curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"orderbook\",\"type\":\"record\",\"name\":\"orderbook_update\",\"fields\":[{\"name\":\"product_id\",\"type\":\"string\"},{\"name\":\"changes\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"map\",\"values\":\"int\"}}},{\"name\":\"time\",\"type\":\"string\"}]}"}' "http://localhost:7002/subjects/orderbook_update-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"match\",\"fields\":[{\"name\":\"maker_order_uuid\",\"type\":\"string\"},{\"name\":\"taker_order_uuid\",\"type\":\"string\"},{\"name\":\"maker_user_id\",\"type\":\"int\"},{\"name\":\"taker_user_id\",\"type\":\"int\"},{\"name\":\"volume\",\"type\":\"int\"},{\"name\":\"price\",\"type\":\"int\"},{\"name\":\"execute_date\",\"type\":\"string\"},{\"name\":\"product_id\",\"type\":\"int\"}]}"}' "http://localhost:7002/subjects/match-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"canceled\",\"fields\":[{\"name\":\"order_uuid\",\"type\":\"string\"},{\"name\":\"user_id\",\"type\":\"int\"},{\"name\":\"cancel_date\",\"type\":\"string\"},{\"name\":\"product_id\",\"type\":\"int\"},{\"name\":\"canceled_volume\",\"type\":\"int\"}]}"}' "http://localhost:7002/subjects/canceled-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"order\",\"fields\":[{\"name\":\"order_uuid\",\"type\":\"string\"},{\"name\":\"product_id\",\"type\":\"int\"},{\"name\":\"user_id\",\"type\":\"int\"},{\"name\":\"volume\",\"type\":[\"null\",\"int\"]},{\"name\":\"create_date\",\"type\":\"string\"},{\"name\":\"side\",\"type\":\"string\"},{\"name\":\"order_type\",\"type\":\"string\"},{\"name\":\"stop_price\",\"type\":[\"null\",\"int\"]},{\"name\":\"price\",\"type\":\"int\"}]}"}' "http://localhost:7002/subjects/order-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"product_news\",\"fields\":[{\"name\":\"news_id\",\"type\":\"long\"},{\"name\":\"product_id\",\"type\":\"int\"}]}"}' "http://localhost:7002/subjects/product_news-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"vote\",\"fields\":[{\"name\":\"product_id\",\"type\":\"int\"},{\"name\":\"poll_id\",\"type\":\"long\"},{\"name\":\"vote_type\",\"type\":\"string\"}]}"}' "http://localhost:7002/subjects/vote-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"offering\",\"fields\":[{\"name\":\"product_id\",\"type\":\"int\"},{\"name\":\"public_offering_id\",\"type\":\"int\"},{\"name\":\"offering_type\",\"type\":\"string\"}]}"}' "http://localhost:7002/subjects/public_offering-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"trade\",\"fields\":[{\"name\":\"product_id\",\"type\":\"int\"},{\"name\":\"user_id\",\"type\":\"int\"},{\"name\":\"order_type\",\"type\":\"string\"},{\"name\":\"side\",\"type\":\"string\"},{\"name\":\"volume\",\"type\":\"int\"},{\"name\":\"execute_date\",\"type\":\"string\"}]}"}' "http://localhost:7002/subjects/trade-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"error\",\"fields\":[{\"name\":\"error_type\",\"type\":[\"null\",\"string\"]},{\"name\":\"error_message\",\"type\":\"string\"},{\"name\":\"module\",\"type\":\"string\"}]}"}' "http://localhost:7002/subjects/error-value/versions" && \
curl -X POST -H "Content-Type:application/vnd.schemaregistry.v1+json" --data '{"schema":"{\"namespace\":\"\",\"type\":\"record\",\"name\":\"push\",\"fields\":[{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"string\"}]}"}' "http://localhost:7002/subjects/push-value/versions"
